security:
 oauth2:
   resource:
     accessTokenUri: http://localhost:8090/auth/oauth/check_token
     userAuthorizationUri: http://localhost:8090/auth/oauth/authorize
     userInfoUri: http://localhost:8090/auth/user
     jwt:
       keyUri: http://localhost:8090/auth/oauth/token_key
server:
 port: 9090
